/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "hef.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ProtoHEFHef, ProtoHEFHef, AUTO)


PB_BIND(ProtoHEFExternalResource, ProtoHEFExternalResource, AUTO)


PB_BIND(ProtoHEFIncludedFeatures, ProtoHEFIncludedFeatures, AUTO)


PB_BIND(ProtoHEFExtension, ProtoHEFExtension, AUTO)


PB_BIND(ProtoHEFOptionalExtension, ProtoHEFOptionalExtension, AUTO)


PB_BIND(ProtoHEFSdkVersion, ProtoHEFSdkVersion, AUTO)


PB_BIND(ProtoHEFRuntimeVersion, ProtoHEFRuntimeVersion, AUTO)


PB_BIND(ProtoHEFHeader, ProtoHEFHeader, AUTO)


PB_BIND(ProtoHEFPhysicalLayout, ProtoHEFPhysicalLayout, AUTO)


PB_BIND(ProtoHEFPartialNetworkGroup, ProtoHEFPartialNetworkGroup, AUTO)


PB_BIND(ProtoHEFPartialCoreOp, ProtoHEFPartialCoreOp, AUTO)


PB_BIND(ProtoHEFCoreOp, ProtoHEFCoreOp, AUTO)


PB_BIND(ProtoHEFYoloBboxDecoder, ProtoHEFYoloBboxDecoder, AUTO)


PB_BIND(ProtoHEFYoloNmsOp, ProtoHEFYoloNmsOp, AUTO)


PB_BIND(ProtoHEFSSDBboxDecoder, ProtoHEFSSDBboxDecoder, AUTO)


PB_BIND(ProtoHEFYoloxBboxDecoder, ProtoHEFYoloxBboxDecoder, AUTO)


PB_BIND(ProtoHEFYoloxNmsOp, ProtoHEFYoloxNmsOp, AUTO)


PB_BIND(ProtoHEFSSDNmsOp, ProtoHEFSSDNmsOp, AUTO)


PB_BIND(ProtoHEFIOUNmsOp, ProtoHEFIOUNmsOp, AUTO)


PB_BIND(ProtoHEFYoloSegProtoInfo, ProtoHEFYoloSegProtoInfo, AUTO)


PB_BIND(ProtoHEFYoloSegNmsOp, ProtoHEFYoloSegNmsOp, AUTO)


PB_BIND(ProtoHEFYolov8BboxDecoder, ProtoHEFYolov8BboxDecoder, AUTO)


PB_BIND(ProtoHEFYolov8NmsOp, ProtoHEFYolov8NmsOp, AUTO)


PB_BIND(ProtoHEFNmsOp, ProtoHEFNmsOp, AUTO)


PB_BIND(ProtoHEFLogitsOp, ProtoHEFLogitsOp, AUTO)


PB_BIND(ProtoHEFTensorShape, ProtoHEFTensorShape, AUTO)


PB_BIND(ProtoHEFNmsShape, ProtoHEFNmsShape, AUTO)


PB_BIND(ProtoHEFPad, ProtoHEFPad, AUTO)


PB_BIND(ProtoHEFOp, ProtoHEFOp, AUTO)


PB_BIND(ProtoHEFPadEdge, ProtoHEFPadEdge, AUTO)


PB_BIND(ProtoHEFNetworkGroup, ProtoHEFNetworkGroup, AUTO)


PB_BIND(ProtoHEFCfgChannelConfig, ProtoHEFCfgChannelConfig, AUTO)


PB_BIND(ProtoHEFNetworkGroupMetadata, ProtoHEFNetworkGroupMetadata, AUTO)


PB_BIND(ProtoHEFFusedLayersMetadata, ProtoHEFFusedLayersMetadata, AUTO)


PB_BIND(ProtoHEFEdgeLayerFused, ProtoHEFEdgeLayerFused, AUTO)


PB_BIND(ProtoHEFContext, ProtoHEFContext, AUTO)


PB_BIND(ProtoHEFOperation, ProtoHEFOperation, AUTO)


PB_BIND(ProtoHEFTrigger, ProtoHEFTrigger, AUTO)


PB_BIND(ProtoHEFTriggerLcu, ProtoHEFTriggerLcu, AUTO)


PB_BIND(ProtoHEFTriggerNms, ProtoHEFTriggerNms, AUTO)


PB_BIND(ProtoHEFTriggerNone, ProtoHEFTriggerNone, AUTO)


PB_BIND(ProtoHEFTriggerAllDataWasSentToHostPCIe, ProtoHEFTriggerAllDataWasSentToHostPCIe, AUTO)


PB_BIND(ProtoHEFTriggerAllDataWasReceivedFromHostPCIe, ProtoHEFTriggerAllDataWasReceivedFromHostPCIe, AUTO)


PB_BIND(ProtoHEFWaitDmaIdleTrigger, ProtoHEFWaitDmaIdleTrigger, AUTO)


PB_BIND(ProtoHEFAction, ProtoHEFAction, AUTO)


PB_BIND(ProtoHEFActionWriteDataCcwPtr, ProtoHEFActionWriteDataCcwPtr, AUTO)


PB_BIND(ProtoHEFActionWriteData, ProtoHEFActionWriteData, AUTO)


PB_BIND(ProtoHEFActionWriteDataCcw, ProtoHEFActionWriteDataCcw, AUTO)


PB_BIND(ProtoHEFActionDebugHalt, ProtoHEFActionDebugHalt, AUTO)


PB_BIND(ProtoHEFActionWriteCompressedData, ProtoHEFActionWriteCompressedData, AUTO)


PB_BIND(ProtoHEFActionDebugSleep, ProtoHEFActionDebugSleep, AUTO)


PB_BIND(ProtoHEFActionDebug, ProtoHEFActionDebug, AUTO)


PB_BIND(ProtoHEFActionWriteDataByType, ProtoHEFActionWriteDataByType, AUTO)


PB_BIND(InitialL3, InitialL3, AUTO)


PB_BIND(ProtoHEFActionEnableSequencer, ProtoHEFActionEnableSequencer, AUTO)


PB_BIND(ProtoHEFActionWaitForSequencer, ProtoHEFActionWaitForSequencer, AUTO)


PB_BIND(ProtoHEFActionWaitForModuleConfigDone, ProtoHEFActionWaitForModuleConfigDone, AUTO)


PB_BIND(ProtoHEFActionDisableLcu, ProtoHEFActionDisableLcu, AUTO)


PB_BIND(ProtoHEFActionEnableLcu, ProtoHEFActionEnableLcu, AUTO)


PB_BIND(ProtoHEFActionSwitchLcuBatch, ProtoHEFActionSwitchLcuBatch, AUTO)


PB_BIND(ProtoHEFActionEnableNMS, ProtoHEFActionEnableNMS, AUTO)


PB_BIND(ProtoHEFActionNone, ProtoHEFActionNone, AUTO)


PB_BIND(ProtoHEFActionDisableDataChannels, ProtoHEFActionDisableDataChannels, AUTO)


PB_BIND(ProtoHEFActionAllowInputDataflow, ProtoHEFActionAllowInputDataflow, AUTO)


PB_BIND(ProtoHEFActionAllowConfigChannel, ProtoHEFActionAllowConfigChannel, AUTO)


PB_BIND(ProtoHEFActionSetDmaCompelte, ProtoHEFActionSetDmaCompelte, AUTO)


PB_BIND(ProtoHEFActionWaitForDmaCompelte, ProtoHEFActionWaitForDmaCompelte, AUTO)


PB_BIND(ProtoHEFPreliminaryConfig, ProtoHEFPreliminaryConfig, AUTO)


PB_BIND(ProtoHEFContextMetadata, ProtoHEFContextMetadata, AUTO)


PB_BIND(ProtoHEFShmiglueInfo, ProtoHEFShmiglueInfo, AUTO)


PB_BIND(ProtoHEFEdgeLayer, ProtoHEFEdgeLayer, AUTO)


PB_BIND(ProtoHEFEdgeLayerInfo, ProtoHEFEdgeLayerInfo, AUTO)


PB_BIND(ProtoHefEdge, ProtoHefEdge, AUTO)


PB_BIND(ProtoHEFEdgeLayerMux, ProtoHEFEdgeLayerMux, AUTO)


PB_BIND(ProtoHEFEdgeLayerPlanes, ProtoHEFEdgeLayerPlanes, AUTO)


PB_BIND(ProtoHEFEdgeLayerMuxData, ProtoHEFEdgeLayerMuxData, AUTO)


PB_BIND(ProtoHEFContextSwitchInformation, ProtoHEFContextSwitchInformation, AUTO)


PB_BIND(ProtoHEFConnectedContextInfo, ProtoHEFConnectedContextInfo, AUTO)


PB_BIND(ProtoHEFResourceIndices, ProtoHEFResourceIndices, AUTO)


PB_BIND(ProtoHEFEdgeLayerBase, ProtoHEFEdgeLayerBase, 2)


PB_BIND(ProtoHEFAdditionalInfo, ProtoHEFAdditionalInfo, AUTO)


PB_BIND(ProtoHEFNmsInfo, ProtoHEFNmsInfo, AUTO)


PB_BIND(ProtoHEFNmsDefuseInfo, ProtoHEFNmsDefuseInfo, AUTO)


PB_BIND(ProtoHEFEdgeLayerNumericInfo, ProtoHEFEdgeLayerNumericInfo, AUTO)


PB_BIND(ProtoHEFOrderedTrigger, ProtoHEFOrderedTrigger, AUTO)


PB_BIND(ProtoHEFClusterEndGuarantee, ProtoHEFClusterEndGuarantee, AUTO)


PB_BIND(ProtoHEFHwPackageInfo, ProtoHEFHwPackageInfo, AUTO)





























#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

