/*
 * hef_parser.h — decode a `.hef` protobuf body into kernel-friendly
 * metadata.
 *
 * The outer header (magic / version / proto_size) is parsed by
 * hef_header.c; this file picks up where that leaves off — given a
 * pointer into the protobuf body and its length, it runs the
 * nanopb decoder (hef.pb.c/h, regenerated by
 * scripts/tools/regen-hef-proto.sh) and pulls out the fields the
 * loader actually cares about:
 *
 *   - hw_arch: the target Hailo device family the HEF was compiled
 *     for. Needed so we can refuse to boot a Hailo-15-only model on
 *     a Hailo-8.
 *   - SDK version string: informational, surfaced by `hailo load`.
 *   - Network group count + first name: proves the proto tree walks
 *     cleanly and gives the shell command something to print.
 *   - First network group's op count.
 *   - First network group's I/O pads with their tensor shapes
 *     (height, width, features + padded variants). Captured up to
 *     HEF_PARSER_MAX_PADS; the loader needs these to size DMA
 *     buffers before submitting an inference.
 *
 * Deeper fields (per-context actions, weight ranges) are decoded
 * in later phases when the loader needs them. Extending the decode
 * is a matter of attaching more pb_callback_t handlers in
 * hef_parser.c.
 */

#ifndef AI_ACCEL_HEF_PARSER_H
#define AI_ACCEL_HEF_PARSER_H

#include <stdint.h>
#include <stddef.h>

/* Error codes — same space as hef_header.h so callers can report a
 * single rc from "parse outer + parse body". */
#define HEF_PARSER_OK              0
#define HEF_PARSER_ERR_INVAL      (-10)  /* NULL blob or bad arg */
#define HEF_PARSER_ERR_DECODE     (-11)  /* nanopb decode failed */
#define HEF_PARSER_ERR_STRING_OVF (-12)  /* a string field exceeded our buffer */

/* Hardware architecture enum values, kept in sync with
 * ProtoHEFHwArch in hef.proto. Listed here (rather than relying on
 * the generated enum) so callers don't have to include 137 KB of
 * hef.pb.h just to switch on hw_arch. */
#define HEF_HW_ARCH_HAILO8         0
#define HEF_HW_ARCH_HAILO8L        1
#define HEF_HW_ARCH_HAILO15H       2
#define HEF_HW_ARCH_HAILO15M       3
#define HEF_HW_ARCH_HAILO10H       4

#define HEF_PARSER_MAX_STR       64   /* longest string we capture */
#define HEF_PARSER_MAX_PAD_NAME  32   /* longest pad-name we capture */
#define HEF_PARSER_MAX_PADS      16   /* cap on pads we record for NG 0 */

/*
 * Cap on ProtoHEFActionWriteDataCcw entries recorded from the first
 * network group's preliminary_config. Typical Hailo-8 models have
 * 30–120 CCW writes (one per layer/weight group); 256 gives us
 * headroom for the biggest Model Zoo entries with a clear truncation
 * signal if a future model overruns. Size cost: 256 × 12 B = 3 KB
 * inside the hef_info stack-allocated aggregate, balanced against
 * the 1.2 KB already consumed by pads[] — well under the 16 KB
 * kernel stack budget.
 */
#define HEF_PARSER_MAX_CCW_ACTIONS 256
/* Cap on the number of HEF contexts whose compute-phase action
 * streams we capture (ProtoHEFContext.operations[].actions[]).
 * A simple MLP emits ~1-2 dynamic contexts; the fixed ACTIVATION/
 * BATCH_SWITCHING/PRELIMINARY preambles don't count here — those
 * are per-context, not per-operation.
 */
#define HEF_PARSER_MAX_CONTEXTS     8
/* Per-context cap on individual actions recorded. A typical MLP
 * compute context emits a dozen actions (enable_sequencer,
 * wait_for_sequencer, enable/disable_lcu, allow_input_dataflow,
 * write_data_by_type, etc.); 64 leaves headroom for larger models. */
#define HEF_PARSER_MAX_CONTEXT_ACTIONS  64

/*
 * One I/O pad of an op inside the first network group.
 *
 * Pads are how Hailo describes the interfaces between compute ops.
 * For the loader's purposes, pads on the "boundary" of the network
 * group are the model's external input/output tensors — they're
 * what determines DMA buffer sizes before we can submit an
 * inference. The kernel doesn't walk pad_edges to pick out
 * boundaries today; it captures every pad of every op in NG 0 (up
 * to HEF_PARSER_MAX_PADS) and defers the boundary-classification
 * work to the future loader.
 *
 * `has_tensor_shape` distinguishes the `ProtoHEFTensorShape` branch
 * of the `shape_info` oneof from the `ProtoHEFNmsShape` branch or
 * an absent shape. When false, the H/W/C dims are all zero.
 */
struct hef_pad_info {
    uint32_t index;                                /* pad index inside op */
    bool     is_input;                             /* true = op's input_pads[] */
    bool     has_tensor_shape;                     /* false = NMS pad or absent */
    char     name[HEF_PARSER_MAX_PAD_NAME];
    uint32_t height;
    uint32_t padded_height;
    uint32_t width;
    uint32_t padded_width;
    uint32_t features;
    uint32_t padded_features;

    /*
     * Phase 6.2b: edge-layer metadata joined in from the first
     * network group's contexts[].metadata.edge_layers[] by pad_index.
     *
     * qp_scale_raw / qp_zp_raw carry the IEEE-754 bit patterns of
     * `float qp_scale` / `float qp_zp` — the parser file is compiled
     * with `-mgeneral-regs-only` and cannot touch float values
     * directly. The FP-capable consumer (kernel/sched/ai/sched_ai.c)
     * converts via memcpy(&scale, &qp_scale_raw, 4).
     *
     * has_quant_info / has_stream_info signal presence independently
     * so consumers can treat each half as optional.
     */
    bool     has_quant_info;
    uint32_t qp_scale_raw;
    uint32_t qp_zp_raw;

    bool     has_stream_info;
    uint32_t sys_index;                /* ProtoHEFEdgeLayerBase.sys_index (f8) */
    uint32_t core_bytes_per_buffer;    /* f9 */
    uint32_t core_buffers_per_frame;   /* f10 */
};

/*
 * One config-channel-word (CCW) write action captured from the
 * first network group's `preliminary_config`. Represents a single
 * `ProtoHEFActionWriteDataCcw` (hef.proto:644) — the Hailo compiler
 * emits one of these per weight region that needs to be DMA'd to
 * the accelerator before inference can start.
 *
 * The `data` bytes themselves are NOT copied into hef_info — with
 * real models that'd be multi-megabyte. Instead we record the byte
 * offset WITHIN the protobuf blob the caller passed to
 * hef_parse_body. The caller (which still owns the blob) can
 * reconstruct `const uint8_t *data = blob_base + data_offset_in_blob`
 * when it's ready to issue the upload.
 *
 * cfg_channel_index selects which firmware-side config channel
 * should receive this blob — set up earlier via CONFIG_STREAM
 * (opcode 0x03) with communication_type=PCIE and the flow type
 * firmware reserves for CFG uploads.
 */
struct hef_ccw_action {
    /* For write_data_ccw (v0/v1 HEF): offset into the proto body
     * (hef_parse_body's `blob` argument), where the payload bytes
     * were embedded inline. For write_data_ccw_ptr (v2+): offset
     * into the CCWS block (the file region following the proto
     * body). `is_ccw_ptr` selects between the two. */
    uint32_t data_offset_in_blob;
    uint32_t data_size;                            /* bytes */
    uint32_t cfg_channel_index;
    bool     cfg_channel_index_known;              /* false = tag absent, treat as 0 */
    bool     is_ccw_ptr;                           /* true = v2+ CCWS-block pointer */
};

/*
 * Per-context action summary (Phase 6.4e). Captures what compute-
 * phase actions each HEF context contains by walking its
 * `operations[].actions[]`. The translator uses this to emit the
 * matching `CONTEXT_SWITCH_DEFS__*` wire actions (EnableLcu,
 * TriggerSequencer, AllowInputDataflow, …).
 *
 * We record the oneof field number per action (the "kind" —
 * 2=write_data, 5=enable_sequencer, 8=enable_lcu, 10=allow_input_
 * dataflow, …; see ProtoHEFAction in hef.proto:602). Per-action
 * parameter extraction lives in separate arrays on hef_info itself
 * (see `enable_lcu_actions` below) to keep the per-context struct
 * small — most actions have no captured parameters in the current
 * translator scope.
 *
 * `action_type_mask` has bit N set if action kind N was seen in
 * this context — a quick sanity-check that lets a caller detect
 * "did this context have any EnableLcu actions?" without scanning
 * the full list.
 */
struct hef_context_actions {
    uint32_t context_index;
    uint32_t action_count;
    uint32_t action_type_mask;
    uint8_t  action_types[HEF_PARSER_MAX_CONTEXT_ACTIONS];
    bool     truncated;           /* action_count exceeded MAX_CONTEXT_ACTIONS */
};

/*
 * One extracted ProtoHEFActionEnableLcu (field 8 of the action
 * oneof). Captures every scalar the HEF carries — the translator
 * combines lcu_index + cluster_index into packed_lcu_id and emits
 * either ENABLE_LCU_DEFAULT (2-byte body: packed_lcu_id +
 * network_index) or ENABLE_LCU_NON_DEFAULT (8-byte body: same plus
 * kernel_done_address + kernel_done_count) depending on whether the
 * kernel-done fields carry non-zero values.
 *
 * `context_index` points back into hef_info.context_actions[] so
 * the translator knows which context this action belongs to. Order
 * within a context is preserved: enable_lcu_actions[] for a given
 * context_index appears in the same order as the corresponding
 * entries in context_actions[context_index].action_types[].
 */
#define HEF_PARSER_MAX_ENABLE_LCU_ACTIONS  32u

struct hef_enable_lcu_action {
    uint8_t  context_index;
    uint32_t lcu_index;
    uint32_t cluster_index;
    uint32_t network_index;
    uint32_t lcu_kernel_done_address;
    uint32_t lcu_kernel_done_count;
    uint32_t lcu_enable_address;
};

/*
 * Distilled metadata from a parsed `.hef` proto body. Owns no
 * dynamic memory; the string fields are inline buffers truncated
 * to HEF_PARSER_MAX_STR-1 bytes with a trailing NUL. If a field
 * exceeds the buffer, the parser sets the truncated flag (low-bit
 * information loss but not a decode error).
 *
 * op_count / pad_count / pads[] describe the FIRST network group
 * only. Subsequent network groups are counted (network_group_count)
 * but their op/pad structure is not captured — the loader runs one
 * network group at a time.
 *
 * Size note: at HEF_PARSER_MAX_PADS=16 and ~64 B per hef_pad_info,
 * this struct is ~1.2 KB. Callers typically declare it as a kernel
 * stack local (shell's `hailo load` does). The 16 KB stack has
 * plenty of room, but future expansion of hef_pad_info or MAX_PADS
 * scales linearly — keep an eye on stack budget if more fields
 * land here.
 */
struct hef_info {
    uint32_t hw_arch;                 /* HEF_HW_ARCH_* */
    bool     hw_arch_known;           /* false if hw_arch was absent */
    char     sdk_version[HEF_PARSER_MAX_STR];
    char     first_network_group[HEF_PARSER_MAX_STR];
    uint32_t network_group_count;
    bool     string_truncated;        /* any str exceeded MAX_STR */
    uint32_t op_count;                /* ops in first network group */
    uint32_t pad_count;               /* valid entries in pads[] */
    bool     pads_truncated;          /* first NG had > MAX_PADS pads */
    struct hef_pad_info pads[HEF_PARSER_MAX_PADS];
    /*
     * CCW write actions from the first network group's
     * `preliminary_config.operation[].actions[].write_data_ccw`.
     * These are the weight-upload units the kernel will issue once
     * Phase 5.3's upload loop is wired. `ccw_total_bytes` sums
     * data_size across recorded entries so a caller can sanity-check
     * model size without iterating. Entries beyond MAX_CCW_ACTIONS
     * are counted (see ccw_actions_truncated) but not stored; the
     * current cap fits every Model Zoo entry the SLM-OS build has
     * been measured against.
     */
    uint32_t ccw_action_count;
    bool     ccw_actions_truncated;
    uint64_t ccw_total_bytes;
    struct hef_ccw_action ccw_actions[HEF_PARSER_MAX_CCW_ACTIONS];
    /*
     * Per-context compute-action summary (Phase 6.4e). Populated
     * from contexts[].operations[].actions[] during hef_parse_body.
     * `context_actions_count` is the number of valid entries in
     * `context_actions[]`. If the HEF has more contexts than
     * HEF_PARSER_MAX_CONTEXTS, the excess are counted (via
     * context_actions_truncated) but not recorded. Each per-context
     * entry has its own `truncated` flag for action-list overflow.
     */
    uint32_t context_actions_count;
    bool     context_actions_truncated;
    struct hef_context_actions context_actions[HEF_PARSER_MAX_CONTEXTS];
    /*
     * Phase 6.4g — per-action parameter capture. Currently only
     * ProtoHEFActionEnableLcu (oneof tag 8) is extracted; other
     * action types are recorded as "kind-only" in context_actions[]
     * above. Each captured EnableLcu records its source context via
     * context_index so the translator can place it correctly when
     * emitting wire actions.
     */
    uint32_t enable_lcu_count;
    bool     enable_lcu_truncated;
    struct hef_enable_lcu_action enable_lcu_actions[HEF_PARSER_MAX_ENABLE_LCU_ACTIONS];
};

/*
 * Decode the proto body at [blob, blob+size) into *out. The blob
 * must be just the protobuf — not the outer HEF header. Typical
 * caller path:
 *
 *   hef_parse_outer_header(file_bytes, file_size, &outer);
 *   hef_parse_body(file_bytes + outer.proto_offset,
 *                  outer.proto_size, &info);
 */
int hef_parse_body(const void *blob, size_t size, struct hef_info *out);

#endif /* AI_ACCEL_HEF_PARSER_H */
