/*
 * hef_parser.h — decode a `.hef` protobuf body into kernel-friendly
 * metadata.
 *
 * The outer header (magic / version / proto_size) is parsed by
 * hef_header.c; this file picks up where that leaves off — given a
 * pointer into the protobuf body and its length, it runs the
 * nanopb decoder (hef.pb.c/h, regenerated by
 * scripts/tools/regen-hef-proto.sh) and pulls out the fields the
 * loader actually cares about:
 *
 *   - hw_arch: the target Hailo device family the HEF was compiled
 *     for. Needed so we can refuse to boot a Hailo-15-only model on
 *     a Hailo-8.
 *   - SDK version string: informational, surfaced by `hailo load`.
 *   - Network group count + first name: proves the proto tree walks
 *     cleanly and gives the shell command something to print.
 *   - First network group's op count.
 *   - First network group's I/O pads with their tensor shapes
 *     (height, width, features + padded variants). Captured up to
 *     HEF_PARSER_MAX_PADS; the loader needs these to size DMA
 *     buffers before submitting an inference.
 *
 * Deeper fields (per-context actions, weight ranges) are decoded
 * in later phases when the loader needs them. Extending the decode
 * is a matter of attaching more pb_callback_t handlers in
 * hef_parser.c.
 */

#ifndef AI_ACCEL_HEF_PARSER_H
#define AI_ACCEL_HEF_PARSER_H

#include <stdint.h>
#include <stddef.h>

/* Error codes — same space as hef_header.h so callers can report a
 * single rc from "parse outer + parse body". */
#define HEF_PARSER_OK              0
#define HEF_PARSER_ERR_INVAL      (-10)  /* NULL blob or bad arg */
#define HEF_PARSER_ERR_DECODE     (-11)  /* nanopb decode failed */
#define HEF_PARSER_ERR_STRING_OVF (-12)  /* a string field exceeded our buffer */

/* Hardware architecture enum values, kept in sync with
 * ProtoHEFHwArch in hef.proto. Listed here (rather than relying on
 * the generated enum) so callers don't have to include 137 KB of
 * hef.pb.h just to switch on hw_arch. */
#define HEF_HW_ARCH_HAILO8         0
#define HEF_HW_ARCH_HAILO8L        1
#define HEF_HW_ARCH_HAILO15H       2
#define HEF_HW_ARCH_HAILO15M       3
#define HEF_HW_ARCH_HAILO10H       4

#define HEF_PARSER_MAX_STR       64   /* longest string we capture */
#define HEF_PARSER_MAX_PAD_NAME  32   /* longest pad-name we capture */
#define HEF_PARSER_MAX_PADS      16   /* cap on pads we record for NG 0 */

/*
 * One I/O pad of an op inside the first network group.
 *
 * Pads are how Hailo describes the interfaces between compute ops.
 * For the loader's purposes, pads on the "boundary" of the network
 * group are the model's external input/output tensors — they're
 * what determines DMA buffer sizes before we can submit an
 * inference. The kernel doesn't walk pad_edges to pick out
 * boundaries today; it captures every pad of every op in NG 0 (up
 * to HEF_PARSER_MAX_PADS) and defers the boundary-classification
 * work to the future loader.
 *
 * `has_tensor_shape` distinguishes the `ProtoHEFTensorShape` branch
 * of the `shape_info` oneof from the `ProtoHEFNmsShape` branch or
 * an absent shape. When false, the H/W/C dims are all zero.
 */
struct hef_pad_info {
    uint32_t index;                                /* pad index inside op */
    bool     is_input;                             /* true = op's input_pads[] */
    bool     has_tensor_shape;                     /* false = NMS pad or absent */
    char     name[HEF_PARSER_MAX_PAD_NAME];
    uint32_t height;
    uint32_t padded_height;
    uint32_t width;
    uint32_t padded_width;
    uint32_t features;
    uint32_t padded_features;
};

/*
 * Distilled metadata from a parsed `.hef` proto body. Owns no
 * dynamic memory; the string fields are inline buffers truncated
 * to HEF_PARSER_MAX_STR-1 bytes with a trailing NUL. If a field
 * exceeds the buffer, the parser sets the truncated flag (low-bit
 * information loss but not a decode error).
 *
 * op_count / pad_count / pads[] describe the FIRST network group
 * only. Subsequent network groups are counted (network_group_count)
 * but their op/pad structure is not captured — the loader runs one
 * network group at a time.
 *
 * Size note: at HEF_PARSER_MAX_PADS=16 and ~64 B per hef_pad_info,
 * this struct is ~1.2 KB. Callers typically declare it as a kernel
 * stack local (shell's `hailo load` does). The 16 KB stack has
 * plenty of room, but future expansion of hef_pad_info or MAX_PADS
 * scales linearly — keep an eye on stack budget if more fields
 * land here.
 */
struct hef_info {
    uint32_t hw_arch;                 /* HEF_HW_ARCH_* */
    bool     hw_arch_known;           /* false if hw_arch was absent */
    char     sdk_version[HEF_PARSER_MAX_STR];
    char     first_network_group[HEF_PARSER_MAX_STR];
    uint32_t network_group_count;
    bool     string_truncated;        /* any str exceeded MAX_STR */
    uint32_t op_count;                /* ops in first network group */
    uint32_t pad_count;               /* valid entries in pads[] */
    bool     pads_truncated;          /* first NG had > MAX_PADS pads */
    struct hef_pad_info pads[HEF_PARSER_MAX_PADS];
};

/*
 * Decode the proto body at [blob, blob+size) into *out. The blob
 * must be just the protobuf — not the outer HEF header. Typical
 * caller path:
 *
 *   hef_parse_outer_header(file_bytes, file_size, &outer);
 *   hef_parse_body(file_bytes + outer.proto_offset,
 *                  outer.proto_size, &info);
 */
int hef_parse_body(const void *blob, size_t size, struct hef_info *out);

#endif /* AI_ACCEL_HEF_PARSER_H */
