/*
 * qmd-selftest-gen.c — Regenerate the reference QMD blob in
 * `kernel/include/ga10b_qmd_selftest_reference.h`, consumed by both
 * the on-device `gpu qmd-selftest` shell verb (kernel/src/shell_sys.c)
 * and the host-side regression check in
 * host-tools/gsp-harness/test_ga10b_bringup.c.
 *
 * Both consumers compare a runtime-encoded QMD against the reference
 * using the same fixed inputs the header pins. This tool prints a
 * drop-in array declaration that exactly matches the consumer
 * header's existing declaration — replace the
 * `ga10b_qmd_selftest_expected` array body in the header with the
 * tool's output and rebuild.
 *
 * Run after any intentional change to `ga10b_qmd_populate` defaults
 * (cache-invalidate bits, version field, etc.). If the host harness's
 * `test_qmd_selftest_reference_matches_encoder` starts failing after
 * such a change, that's the build-time signal that the reference is
 * stale; regenerate, verify the diff matches the intended encoder
 * change, and the on-device `gpu qmd-selftest` will pass on next
 * deploy.
 *
 *   gcc -std=c11 -Wall -O0 -I. \
 *       -o /tmp/qmd-selftest-gen \
 *       scripts/tools/qmd-selftest-gen.c \
 *       kernel/gpu/nvidia/ga10b_qmd.c
 *   /tmp/qmd-selftest-gen
 *
 * The fixed inputs (shader_gpu_va, cbuf_gpu_va, register_count_v,
 * grid/block dims) live as `GA10B_QMD_SELFTEST_*` macros in the
 * consumer header so the generator and consumers stay in lock-step
 * by reference rather than by copy. They're arbitrary but chosen so
 * every non-trivial encoded field is set — no relation to MNIST's
 * actual launch parameters. The reference blob's purpose is to
 * detect *encoder* regressions, not to exercise any specific GPU
 * code path.
 */

#include <stdio.h>

#include "kernel/gpu/nvidia/ga10b_qmd.h"
#include "kernel/include/ga10b_qmd_selftest_reference.h"

int main(void)
{
    uint32_t qmd[GA10B_QMD_DWORDS];
    ga10b_qmd_populate(qmd,
                       GA10B_QMD_SELFTEST_SHADER_GPU_VA,
                       GA10B_QMD_SELFTEST_CBUF_GPU_VA,
                       GA10B_QMD_SELFTEST_REGISTER_COUNT,
                       GA10B_QMD_SELFTEST_GRID_X,
                       GA10B_QMD_SELFTEST_GRID_Y,
                       GA10B_QMD_SELFTEST_GRID_Z,
                       GA10B_QMD_SELFTEST_BLOCK_X,
                       GA10B_QMD_SELFTEST_BLOCK_Y,
                       GA10B_QMD_SELFTEST_BLOCK_Z);

    /* Drop-in replacement for the existing array declaration in
     * kernel/include/ga10b_qmd_selftest_reference.h. */
    printf("/* Generated by scripts/tools/qmd-selftest-gen.c —\n");
    printf(" * see top-of-file comment for regen instructions. */\n");
    printf("static const uint32_t "
           "ga10b_qmd_selftest_expected[GA10B_QMD_DWORDS] = {\n");
    for (unsigned i = 0; i < GA10B_QMD_DWORDS; i++) {
        if (i % 4 == 0) printf("    ");
        printf("0x%08xu,", qmd[i]);
        if (i % 4 == 3) printf("\n");
        else printf(" ");
    }
    printf("};\n");
    return 0;
}
