/*
 * qmd-selftest-gen.c — Regenerate the reference QMD blob baked into
 * `gpu qmd-selftest` (kernel/src/shell_sys.c).
 *
 * The shell verb compares a runtime-encoded QMD against a fixed
 * 256-byte reference. This tool prints that reference as a C array
 * suitable for pasting back into shell_sys.c.
 *
 * Run after any intentional change to `ga10b_qmd_populate` defaults
 * (cache-invalidate bits, version field, etc.). If the runtime
 * `gpu qmd-selftest` starts failing on hardware after such a change,
 * regenerate the reference and verify the diff matches the intended
 * encoder change.
 *
 *   gcc -std=c11 -Wall -O0 -I. \
 *       -o /tmp/qmd-selftest-gen \
 *       scripts/tools/qmd-selftest-gen.c \
 *       kernel/gpu/nvidia/ga10b_qmd.c
 *   /tmp/qmd-selftest-gen
 *
 * The fixed inputs (shader_gpu_va, cbuf_gpu_va, register_count_v,
 * grid/block dims) are intentionally arbitrary but chosen so every
 * non-trivial encoded field is set — they have no relation to the
 * MNIST kernel's actual launch parameters. The reference blob's
 * purpose is to detect *encoder* regressions, not to exercise any
 * specific GPU code path.
 */

#include <stdio.h>

#include "kernel/gpu/nvidia/ga10b_qmd.h"

int main(void)
{
    uint32_t qmd[GA10B_QMD_DWORDS];
    ga10b_qmd_populate(qmd,
                       0x12340000ULL,  /* shader_gpu_va */
                       0x56780000ULL,  /* cbuf_gpu_va */
                       64u,            /* register_count_v */
                       1u, 1u, 1u,     /* grid x/y/z */
                       32u, 1u, 1u);   /* block x/y/z */

    printf("/* Generated by scripts/tools/qmd-selftest-gen.c —\n");
    printf(" * see top-of-file comment for regen instructions. */\n");
    printf("static const uint32_t expected[64] = {\n");
    for (unsigned i = 0; i < GA10B_QMD_DWORDS; i++) {
        if (i % 4 == 0) printf("    ");
        printf("0x%08xu,", qmd[i]);
        if (i % 4 == 3) printf("\n");
        else printf(" ");
    }
    printf("};\n");
    return 0;
}
