/*
 * ga10b_qmd_selftest_reference.h — Reference QMD blob for the
 * `gpu qmd-selftest` shell verb (kernel/src/shell_sys.c) and the
 * matching host-side regression check (host-tools/gsp-harness/
 * test_ga10b_bringup.c).
 *
 * Both consumers compare a freshly-encoded QMD against this
 * reference using the same fixed inputs:
 *
 *   shader_gpu_va = 0x12340000
 *   cbuf_gpu_va   = 0x56780000
 *   register_count_v = 64
 *   grid  = (1, 1, 1)
 *   block = (32, 1, 1)
 *
 * The host test re-runs `ga10b_qmd_populate` with these inputs and
 * byte-compares against this same blob, catching the "intentional
 * encoder change but forgot to regenerate the reference" failure
 * mode at build time. The shell verb does the same thing on real
 * hardware to catch AArch64 corner cases / memory corruption.
 *
 * Regenerate after any intentional change to `ga10b_qmd_populate`
 * defaults: see `scripts/tools/qmd-selftest-gen.c` for the command
 * line; paste the resulting array body in below.
 */

#ifndef GA10B_QMD_SELFTEST_REFERENCE_H
#define GA10B_QMD_SELFTEST_REFERENCE_H

#include <stdint.h>

#include "../gpu/nvidia/ga10b_qmd.h"  /* GA10B_QMD_DWORDS */

#define GA10B_QMD_SELFTEST_SHADER_GPU_VA   0x12340000ULL
#define GA10B_QMD_SELFTEST_CBUF_GPU_VA     0x56780000ULL
#define GA10B_QMD_SELFTEST_REGISTER_COUNT  64u
#define GA10B_QMD_SELFTEST_GRID_X          1u
#define GA10B_QMD_SELFTEST_GRID_Y          1u
#define GA10B_QMD_SELFTEST_GRID_Z          1u
#define GA10B_QMD_SELFTEST_BLOCK_X         32u
#define GA10B_QMD_SELFTEST_BLOCK_Y         1u
#define GA10B_QMD_SELFTEST_BLOCK_Z         1u

/* Generated by scripts/tools/qmd-selftest-gen.c — see top-of-file
 * comment for regen instructions. */
static const uint32_t ga10b_qmd_selftest_expected[GA10B_QMD_DWORDS] = {
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000040u, 0xfc000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x04010000u,
    0x00000001u, 0x00000001u, 0x00000001u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00200030u, 0x00010001u,
    0x00004001u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x56780000u, 0x01040000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x12340000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
};

#endif /* GA10B_QMD_SELFTEST_REFERENCE_H */
