# Generate kernel/include/build_info.h from version.txt + git state + UTC stamp.
# Invoked by the `generate_build_info` custom target on every build.
#
# Required cache vars (passed via -D):
#   SRC_DIR  — repository root (where version.txt lives)
#   OUT_FILE — absolute path to the header to write

if(NOT DEFINED SRC_DIR OR NOT DEFINED OUT_FILE)
    message(FATAL_ERROR "gen_build_info.cmake requires -DSRC_DIR=... -DOUT_FILE=...")
endif()

# --- Version: first non-blank line of version.txt --------------------------
if(NOT EXISTS "${SRC_DIR}/version.txt")
    message(FATAL_ERROR "version.txt not found at ${SRC_DIR}/version.txt")
endif()

file(STRINGS "${SRC_DIR}/version.txt" _version_lines)
set(_version "")
foreach(_line ${_version_lines})
    string(STRIP "${_line}" _stripped)
    if(NOT "${_stripped}" STREQUAL "")
        set(_version "${_stripped}")
        break()
    endif()
endforeach()
if(_version STREQUAL "")
    message(FATAL_ERROR "version.txt has no non-blank line")
endif()

# --- UTC build stamp (14 chars, string-sortable) ----------------------------
# Wall-clock UTC; intentionally NOT honoring SOURCE_DATE_EPOCH. The point of
# this header is to *distinguish* otherwise-identical builds, so reproducible
# timestamps would defeat the purpose. Reproducible-builds work would need a
# separate code path here.
string(TIMESTAMP _stamp "%Y%m%d%H%M%S" UTC)
string(LENGTH "${_stamp}" _stamp_len)
if(NOT _stamp_len EQUAL 14)
    message(FATAL_ERROR "Generated build stamp '${_stamp}' is not 14 chars (got ${_stamp_len})")
endif()

# --- Git short SHA, with -dirty suffix when working tree is unclean --------
# Untracked files count as dirty: an uncommitted source file changes what got
# compiled, so the SHA alone would lie. Use .gitignore to exclude noise (build
# artifacts, editor swap files) rather than masking the dirty bit here.
find_package(Git QUIET)
set(_sha "unknown")
if(NOT Git_FOUND)
    message(WARNING
        "gen_build_info: git not found on PATH; SLMOS_BUILD_SHA = 'unknown'")
else()
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
        WORKING_DIRECTORY ${SRC_DIR}
        OUTPUT_VARIABLE _sha_out
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_VARIABLE  _sha_err
        RESULT_VARIABLE _sha_result
    )
    if(_sha_result EQUAL 0 AND NOT "${_sha_out}" STREQUAL "")
        set(_sha "${_sha_out}")
    else()
        message(WARNING
            "gen_build_info: git rev-parse failed (rc=${_sha_result}, err='${_sha_err}'); "
            "SLMOS_BUILD_SHA = 'unknown'")
    endif()

    execute_process(
        COMMAND ${GIT_EXECUTABLE} status --porcelain
        WORKING_DIRECTORY ${SRC_DIR}
        OUTPUT_VARIABLE _git_status
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_VARIABLE  _status_err
        RESULT_VARIABLE _status_result
    )
    if(NOT _status_result EQUAL 0)
        message(WARNING
            "gen_build_info: git status failed (rc=${_status_result}, err='${_status_err}'); "
            "cannot detect dirty tree")
    elseif(NOT "${_git_status}" STREQUAL "")
        set(_sha "${_sha}-dirty")
    endif()
endif()

# --- Header content ---------------------------------------------------------
set(_content
"/* Generated by cmake/gen_build_info.cmake — do not edit. SLMOS_BUILD_STAMP is UTC. */
#pragma once
#define SLMOS_VERSION     \"${_version}\"
#define SLMOS_BUILD_STAMP \"${_stamp}\"
#define SLMOS_BUILD_SHA   \"${_sha}\"
")

# Avoid spurious relinks when the build runs inside the same UTC second
# (e.g. successive cmake reconfigures): only rewrite the header when the
# new content actually differs from what is already on disk.
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" _existing)
    if("${_existing}" STREQUAL "${_content}")
        return()
    endif()
endif()
file(WRITE "${OUT_FILE}" "${_content}")
