/* ai_config.h — Auto-generated by export_models.py */
#ifndef AI_CONFIG_H
#define AI_CONFIG_H

#define AI_SCHED_STATE_SIZE  108
#define AI_SCHED_N_ACTIONS   42
#define AI_SCHED_PLATFORM    "jetson_orin_nano"
#define AI_SCHED_N_CORES     6
#define AI_SCHED_GPU         1

struct ai_sched_action {
    unsigned char core_assignment;  /* 0..N_CORES-1, or N_CORES for GPU */
    unsigned char priority_adj;     /* 0=lower, 1=keep, 2=raise */
    unsigned char preempt;          /* 1=preempt current task on core */
};

/* Decode flat action index → structured action.
 * Encoding: idx = core * 6 + priority_adj * 2 + preempt
 * Action space: (6 cores + 1 GPU) × 3 priority × 2 preempt = 42
 */
static inline void ai_decode_action(int idx, struct ai_sched_action *out) {
    out->preempt        = idx % 2;  idx /= 2;
    out->priority_adj   = idx % 3;  idx /= 3;
    out->core_assignment = idx;
}

#endif /* AI_CONFIG_H */
