/* ai_config.h — Auto-generated by export_models.py, with per-platform
 * overrides hand-edited for Pi 5 (4 cores, no GPU) vs Jetson (6 cores,
 * GPU present). The in-tree weights (ai_weights_mlp.c) are 42-action;
 * Pi 5 reads only the first 24 rows of w3 — which matches the
 * 24-action scheduler_mlp_pi5.hef produced by our DFC pipeline.
 */
#ifndef AI_CONFIG_H
#define AI_CONFIG_H

#define AI_SCHED_STATE_SIZE  108

#if defined(PLATFORM_RASPI5)
/* Pi 5: 4 cores, no GPU → (4 + 0) × 3 priorities × 2 preempt = 24. */
#define AI_SCHED_N_ACTIONS   24
#define AI_SCHED_PLATFORM    "raspi5"
#define AI_SCHED_N_CORES     4
#define AI_SCHED_GPU         0
#else
/* Jetson / QEMU default: 6 cores + GPU = 42. */
#define AI_SCHED_N_ACTIONS   42
#define AI_SCHED_PLATFORM    "jetson_orin_nano"
#define AI_SCHED_N_CORES     6
#define AI_SCHED_GPU         1
#endif

struct ai_sched_action {
    unsigned char core_assignment;  /* 0..N_CORES-1, or N_CORES for GPU */
    unsigned char priority_adj;     /* 0=lower, 1=keep, 2=raise */
    unsigned char preempt;          /* 1=preempt current task on core */
};

/* Decode flat action index → structured action.
 * Encoding: idx = core * 6 + priority_adj * 2 + preempt
 * Action space: (6 cores + 1 GPU) × 3 priority × 2 preempt = 42
 */
static inline void ai_decode_action(int idx, struct ai_sched_action *out) {
    out->preempt        = idx % 2;  idx /= 2;
    out->priority_adj   = idx % 3;  idx /= 3;
    out->core_assignment = idx;
}

#endif /* AI_CONFIG_H */
