/*
 * ai_weights.h - Weight array declarations for AI scheduler models
 *
 * Extern declarations for the weight and bias arrays used by the MLP
 * and PPO inference functions. The actual arrays are defined in either:
 *   - ai_weights_stub.c (all zeros, for development)
 *   - ai_weights_mlp.c  (real weights, generated by Plan A export)
 *
 * All arrays are const — weights are read-only at inference time.
 * Arrays are aligned to 64 bytes for cache-line-friendly access.
 */

#ifndef AI_WEIGHTS_H
#define AI_WEIGHTS_H

#include "ai_types.h"

/* ============================================================================
 * MLP weights (4-layer feed-forward network)
 * ============================================================================ */

/* Layer 0: 108 -> 256 */
extern const float ai_mlp_w0[AI_MLP_LAYER0_OUT * AI_MLP_LAYER0_IN];
extern const float ai_mlp_b0[AI_MLP_LAYER0_OUT];

/* Layer 1: 256 -> 256 */
extern const float ai_mlp_w1[AI_MLP_LAYER1_OUT * AI_MLP_LAYER1_IN];
extern const float ai_mlp_b1[AI_MLP_LAYER1_OUT];

/* Layer 2: 256 -> 128 */
extern const float ai_mlp_w2[AI_MLP_LAYER2_OUT * AI_MLP_LAYER2_IN];
extern const float ai_mlp_b2[AI_MLP_LAYER2_OUT];

/* Layer 3: 128 -> N_ACTIONS_MAX. The in-tree arrays are sized for the
 * 42-action Jetson/QEMU space; Pi 5 (AI_SCHED_N_ACTIONS=24) reads
 * only the first 24 rows of w3 / first 24 entries of b3. Declaring
 * the extern with the physical 42-row size is what ai_weights_mlp.c
 * actually emits — decoupling from AI_SCHED_N_ACTIONS prevents a
 * conflicting-type error when the platform override reduces the
 * action count. */
#define AI_MLP_LAYER3_MAX_ROWS  42
extern const float ai_mlp_w3[AI_MLP_LAYER3_MAX_ROWS * AI_MLP_LAYER3_IN];
extern const float ai_mlp_b3[AI_MLP_LAYER3_MAX_ROWS];

/* ============================================================================
 * PPO weights (same architecture as MLP, different learned values)
 * ============================================================================ */

extern const float ai_ppo_w0[AI_MLP_LAYER0_OUT * AI_MLP_LAYER0_IN];
extern const float ai_ppo_b0[AI_MLP_LAYER0_OUT];

extern const float ai_ppo_w1[AI_MLP_LAYER1_OUT * AI_MLP_LAYER1_IN];
extern const float ai_ppo_b1[AI_MLP_LAYER1_OUT];

extern const float ai_ppo_w2[AI_MLP_LAYER2_OUT * AI_MLP_LAYER2_IN];
extern const float ai_ppo_b2[AI_MLP_LAYER2_OUT];

extern const float ai_ppo_w3[AI_MLP_LAYER3_MAX_ROWS * AI_MLP_LAYER3_IN];
extern const float ai_ppo_b3[AI_MLP_LAYER3_MAX_ROWS];

#endif /* AI_WEIGHTS_H */
