/*
 * ai_weights.h - Weight array declarations for AI scheduler models
 *
 * Extern declarations for the weight and bias arrays used by the MLP
 * and PPO inference functions. The actual arrays are defined in either:
 *   - ai_weights_stub.c (all zeros, for development)
 *   - ai_weights_mlp.c  (real weights, generated by Plan A export)
 *
 * All arrays are const — weights are read-only at inference time.
 * Arrays are aligned to 64 bytes for cache-line-friendly access.
 */

#ifndef AI_WEIGHTS_H
#define AI_WEIGHTS_H

#include "ai_types.h"

/* ============================================================================
 * MLP weights (4-layer feed-forward network)
 * ============================================================================ */

/* Layer 0: 108 -> 256 */
extern const float ai_mlp_w0[AI_MLP_LAYER0_OUT * AI_MLP_LAYER0_IN];
extern const float ai_mlp_b0[AI_MLP_LAYER0_OUT];

/* Layer 1: 256 -> 256 */
extern const float ai_mlp_w1[AI_MLP_LAYER1_OUT * AI_MLP_LAYER1_IN];
extern const float ai_mlp_b1[AI_MLP_LAYER1_OUT];

/* Layer 2: 256 -> 128 */
extern const float ai_mlp_w2[AI_MLP_LAYER2_OUT * AI_MLP_LAYER2_IN];
extern const float ai_mlp_b2[AI_MLP_LAYER2_OUT];

/* Layer 3: 128 -> N_ACTIONS */
extern const float ai_mlp_w3[AI_MLP_LAYER3_OUT * AI_MLP_LAYER3_IN];
extern const float ai_mlp_b3[AI_MLP_LAYER3_OUT];

/* ============================================================================
 * PPO weights (same architecture as MLP, different learned values)
 * ============================================================================ */

extern const float ai_ppo_w0[AI_MLP_LAYER0_OUT * AI_MLP_LAYER0_IN];
extern const float ai_ppo_b0[AI_MLP_LAYER0_OUT];

extern const float ai_ppo_w1[AI_MLP_LAYER1_OUT * AI_MLP_LAYER1_IN];
extern const float ai_ppo_b1[AI_MLP_LAYER1_OUT];

extern const float ai_ppo_w2[AI_MLP_LAYER2_OUT * AI_MLP_LAYER2_IN];
extern const float ai_ppo_b2[AI_MLP_LAYER2_OUT];

extern const float ai_ppo_w3[AI_MLP_LAYER3_OUT * AI_MLP_LAYER3_IN];
extern const float ai_ppo_b3[AI_MLP_LAYER3_OUT];

#endif /* AI_WEIGHTS_H */
